// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/forwarder.proto

package forwarder

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	mi := &file_proto_forwarder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwarder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_proto_forwarder_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DataRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type DataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	mi := &file_proto_forwarder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwarder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_proto_forwarder_proto_rawDescGZIP(), []int{1}
}

func (x *DataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_forwarder_proto protoreflect.FileDescriptor

const file_proto_forwarder_proto_rawDesc = "" +
	"\n" +
	"\x15proto/forwarder.proto\x12\tforwarder\"D\n" +
	"\vDataRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"(\n" +
	"\fDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2H\n" +
	"\tForwarder\x12;\n" +
	"\bSendData\x12\x16.forwarder.DataRequest\x1a\x17.forwarder.DataResponseB\x13Z\x11./proto;forwarderb\x06proto3"

var (
	file_proto_forwarder_proto_rawDescOnce sync.Once
	file_proto_forwarder_proto_rawDescData []byte
)

func file_proto_forwarder_proto_rawDescGZIP() []byte {
	file_proto_forwarder_proto_rawDescOnce.Do(func() {
		file_proto_forwarder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_forwarder_proto_rawDesc), len(file_proto_forwarder_proto_rawDesc)))
	})
	return file_proto_forwarder_proto_rawDescData
}

var file_proto_forwarder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_forwarder_proto_goTypes = []any{
	(*DataRequest)(nil),  // 0: forwarder.DataRequest
	(*DataResponse)(nil), // 1: forwarder.DataResponse
}
var file_proto_forwarder_proto_depIdxs = []int32{
	0, // 0: forwarder.Forwarder.SendData:input_type -> forwarder.DataRequest
	1, // 1: forwarder.Forwarder.SendData:output_type -> forwarder.DataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_forwarder_proto_init() }
func file_proto_forwarder_proto_init() {
	if File_proto_forwarder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_forwarder_proto_rawDesc), len(file_proto_forwarder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_forwarder_proto_goTypes,
		DependencyIndexes: file_proto_forwarder_proto_depIdxs,
		MessageInfos:      file_proto_forwarder_proto_msgTypes,
	}.Build()
	File_proto_forwarder_proto = out.File
	file_proto_forwarder_proto_goTypes = nil
	file_proto_forwarder_proto_depIdxs = nil
}
